
long secondes;
int années;
int mois;
int jours;
int heures;
int minutes;
Console.WriteLine("On va convertir une durée (en secondes) en années");
Console.WriteLine("Donnez votre valeur en secondes :");
secondes = Convert.ToInt64(Console.ReadLine());
années = (int)(secondes / (352*24*60*60));
long resteSecondesMois = secondes % (352*24*60*60);
mois = (int)(resteSecondesMois / (30*24*60*60));
long resteSecondesJours = resteSecondesMois % (30*24*60*60);
jours = (int)(resteSecondesJours / (24*60*60));
int resteSecondesHeures = (int)(resteSecondesJours % (24*60*60));
heures = (int)(resteSecondesHeures / (60*60));
int resteSecondesMinutes = (int)(resteSecondesHeures) % (60*60);
minutes = (int)(resteSecondesMinutes / 60);
int resteSecondes = (int)(resteSecondesMinutes) % 60;
Console.WriteLine("Nombre d'années :" + années);
Console.WriteLine("Nombre de mois :" + mois);
Console.WriteLine("Nombre de jours :" + jours);
Console.WriteLine("Nombre d'heures :" + heures);
Console.WriteLine("Nombre de minutes :" + minutes);
Console.WriteLine("Nombre de secondes :" + resteSecondes);
